# Generated by Django 4.2 on 2023-04-22 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science and Engineering"),
                            ("ECE", "Electronics and Communication Engineering"),
                            ("EEE", "Electrical and Electronics Engineering"),
                            ("ME", "Mechanical Engineering"),
                            ("CE", "Civil Engineering"),
                            ("IT", "Information Technology"),
                            ("ECS", "Electronics and Computer Science Engineering"),
                        ],
                        default="ECS",
                        max_length=50,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classes.semester",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="subjects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
