# Generated by Django 4.2 on 2023-04-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="semester",
            field=models.CharField(max_length=5),
        ),
    ]
