# Generated by Django 4.2 on 2023-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0004_code_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="code",
            field=models.CharField(default="", max_length=255),
        ),
    ]
