# Generated by Django 4.2 on 2023-04-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classes", "0006_remove_code_end_time_remove_code_start_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="code",
            name="end_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AddField(
            model_name="code",
            name="start_time",
            field=models.TimeField(default="00:00:00"),
        ),
        migrations.AlterField(
            model_name="code",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
