# Generated by Django 4.2 on 2023-04-24 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_roll_no"),
        ("classes", "0007_code_end_time_code_start_time_alter_code_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.user"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="students",
            field=models.ManyToManyField(related_name="subjects", to="users.user"),
        ),
    ]
